# Site settings

# Site settings
title: birknbasil
url: www.birknbasil.club
description: "testinggggg."


paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 


# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
